spring:
  application:
    name: inventory-service

  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/yodb_inventory
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5


#otel:
#  exporter:
#    otlp:
#      endpoint: http://localhost:4317
#  distribution:
#    spring_starter:
#      instrumentation:
#        default_enabled: false
#        enabled:
#          - jdbc
#          - spring_web
